/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from 'ethers'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'
import { TypedEventFilter, TypedEvent, TypedListener } from './commons'

export interface AcademyProjectListInterface extends ethers.utils.Interface {
  functions: {
    'DEFAULT_ADMIN_ROLE()': FunctionFragment
    'getRoleAdmin(bytes32)': FunctionFragment
    'getRoleMember(bytes32,uint256)': FunctionFragment
    'getRoleMemberCount(bytes32)': FunctionFragment
    'grantRole(bytes32,address)': FunctionFragment
    'hasRole(bytes32,address)': FunctionFragment
    'renounceRole(bytes32,address)': FunctionFragment
    'revokeRole(bytes32,address)': FunctionFragment
    'addProject(string,string)': FunctionFragment
    'delProject(string)': FunctionFragment
    'updateProjectByName(string,bool,address,string,string)': FunctionFragment
    'changeActive()': FunctionFragment
    'exists(string)': FunctionFragment
    'isActive(string)': FunctionFragment
    'getProjectByName(string)': FunctionFragment
    'getMasterAddressByName(string)': FunctionFragment
    'getProjectByIndex(uint256)': FunctionFragment
    'getIndexByName(string)': FunctionFragment
    'countProjects()': FunctionFragment
    'listProjects()': FunctionFragment
  }

  encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string
  encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string
  encodeFunctionData(functionFragment: 'getRoleMember', values: [BytesLike, BigNumberish]): string
  encodeFunctionData(functionFragment: 'getRoleMemberCount', values: [BytesLike]): string
  encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 'addProject', values: [string, string]): string
  encodeFunctionData(functionFragment: 'delProject', values: [string]): string
  encodeFunctionData(functionFragment: 'updateProjectByName', values: [string, boolean, string, string, string]): string
  encodeFunctionData(functionFragment: 'changeActive', values?: undefined): string
  encodeFunctionData(functionFragment: 'exists', values: [string]): string
  encodeFunctionData(functionFragment: 'isActive', values: [string]): string
  encodeFunctionData(functionFragment: 'getProjectByName', values: [string]): string
  encodeFunctionData(functionFragment: 'getMasterAddressByName', values: [string]): string
  encodeFunctionData(functionFragment: 'getProjectByIndex', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'getIndexByName', values: [string]): string
  encodeFunctionData(functionFragment: 'countProjects', values?: undefined): string
  encodeFunctionData(functionFragment: 'listProjects', values?: undefined): string

  decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getRoleMember', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getRoleMemberCount', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'addProject', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'delProject', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'updateProjectByName', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'changeActive', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'exists', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'isActive', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getProjectByName', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getMasterAddressByName', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getProjectByIndex', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getIndexByName', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'countProjects', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'listProjects', data: BytesLike): Result

  events: {
    'ProjectAdded(string,string)': EventFragment
    'ProjectDeleted(string)': EventFragment
    'ProjectUpdated(string,string,address,bool)': EventFragment
    'RoleAdminChanged(bytes32,bytes32,bytes32)': EventFragment
    'RoleGranted(bytes32,address,address)': EventFragment
    'RoleRevoked(bytes32,address,address)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'ProjectAdded'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'ProjectDeleted'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'ProjectUpdated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RoleAdminChanged'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RoleGranted'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RoleRevoked'): EventFragment
}

export interface AcademyProjectListType extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>,
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
  ): this

  listeners(eventName?: string): Array<Listener>
  off(eventName: string, listener: Listener): this
  on(eventName: string, listener: Listener): this
  once(eventName: string, listener: Listener): this
  removeListener(eventName: string, listener: Listener): this
  removeAllListeners(eventName?: string): this

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>

  interface: AcademyProjectListInterface

  functions: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>

    /**
     * Returns the admin role that controls `role`. See {grantRole} and {revokeRole}. To change a role's admin, use {_setRoleAdmin}.
     */
    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>

    /**
     * Returns one of the accounts that have `role`. `index` must be a value between 0 and {getRoleMemberCount}, non-inclusive. Role bearers are not sorted in any particular way, and their ordering may change at any point. WARNING: When using {getRoleMember} and {getRoleMemberCount}, make sure you perform all queries on the same block. See the following https://forum.openzeppelin.com/t/iterating-over-elements-on-enumerableset-in-openzeppelin-contracts/2296[forum post] for more information.
     */
    getRoleMember(role: BytesLike, index: BigNumberish, overrides?: CallOverrides): Promise<[string]>

    /**
     * Returns the number of accounts that have `role`. Can be used together with {getRoleMember} to enumerate all bearers of a role.
     */
    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<[BigNumber]>

    /**
     * Grants `role` to `account`. If `account` had not been already granted `role`, emits a {RoleGranted} event. Requirements: - the caller must have ``role``'s admin role.
     */
    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    /**
     * Returns `true` if `account` has been granted `role`.
     */
    hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<[boolean]>

    /**
     * Revokes `role` from the calling account. Roles are often managed via {grantRole} and {revokeRole}: this function's purpose is to provide a mechanism for accounts to lose their privileges if they are compromised (such as when a trusted device is misplaced). If the calling account had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must be `account`.
     */
    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    /**
     * Revokes `role` from `account`. If `account` had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must have ``role``'s admin role.
     */
    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    addProject(
      name: string,
      description: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    delProject(name: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

    updateProjectByName(
      name: string,
      activeProject: boolean,
      master: string,
      description: string,
      ABI: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    changeActive(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

    exists(name: string, overrides?: CallOverrides): Promise<[boolean]>

    isActive(name: string, overrides?: CallOverrides): Promise<[boolean]>

    getProjectByName(
      name: string,
      overrides?: CallOverrides,
    ): Promise<
      [
        [boolean, string, string, string, string] & {
          active: boolean
          master: string
          name: string
          description: string
          ABI: string
        },
      ]
    >

    getMasterAddressByName(name: string, overrides?: CallOverrides): Promise<[string]>

    getProjectByIndex(
      index: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [
        [boolean, string, string, string, string] & {
          active: boolean
          master: string
          name: string
          description: string
          ABI: string
        },
      ]
    >

    getIndexByName(name: string, overrides?: CallOverrides): Promise<[BigNumber]>

    countProjects(overrides?: CallOverrides): Promise<[BigNumber]>

    listProjects(
      overrides?: CallOverrides,
    ): Promise<
      [
        ([boolean, string, string, string, string] & {
          active: boolean
          master: string
          name: string
          description: string
          ABI: string
        })[],
      ]
    >
  }

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>

  /**
   * Returns the admin role that controls `role`. See {grantRole} and {revokeRole}. To change a role's admin, use {_setRoleAdmin}.
   */
  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>

  /**
   * Returns one of the accounts that have `role`. `index` must be a value between 0 and {getRoleMemberCount}, non-inclusive. Role bearers are not sorted in any particular way, and their ordering may change at any point. WARNING: When using {getRoleMember} and {getRoleMemberCount}, make sure you perform all queries on the same block. See the following https://forum.openzeppelin.com/t/iterating-over-elements-on-enumerableset-in-openzeppelin-contracts/2296[forum post] for more information.
   */
  getRoleMember(role: BytesLike, index: BigNumberish, overrides?: CallOverrides): Promise<string>

  /**
   * Returns the number of accounts that have `role`. Can be used together with {getRoleMember} to enumerate all bearers of a role.
   */
  getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

  /**
   * Grants `role` to `account`. If `account` had not been already granted `role`, emits a {RoleGranted} event. Requirements: - the caller must have ``role``'s admin role.
   */
  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  /**
   * Returns `true` if `account` has been granted `role`.
   */
  hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<boolean>

  /**
   * Revokes `role` from the calling account. Roles are often managed via {grantRole} and {revokeRole}: this function's purpose is to provide a mechanism for accounts to lose their privileges if they are compromised (such as when a trusted device is misplaced). If the calling account had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must be `account`.
   */
  renounceRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  /**
   * Revokes `role` from `account`. If `account` had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must have ``role``'s admin role.
   */
  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  addProject(
    name: string,
    description: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  delProject(name: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

  updateProjectByName(
    name: string,
    activeProject: boolean,
    master: string,
    description: string,
    ABI: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  changeActive(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

  exists(name: string, overrides?: CallOverrides): Promise<boolean>

  isActive(name: string, overrides?: CallOverrides): Promise<boolean>

  getProjectByName(
    name: string,
    overrides?: CallOverrides,
  ): Promise<
    [boolean, string, string, string, string] & {
      active: boolean
      master: string
      name: string
      description: string
      ABI: string
    }
  >

  getMasterAddressByName(name: string, overrides?: CallOverrides): Promise<string>

  getProjectByIndex(
    index: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<
    [boolean, string, string, string, string] & {
      active: boolean
      master: string
      name: string
      description: string
      ABI: string
    }
  >

  getIndexByName(name: string, overrides?: CallOverrides): Promise<BigNumber>

  countProjects(overrides?: CallOverrides): Promise<BigNumber>

  listProjects(
    overrides?: CallOverrides,
  ): Promise<
    ([boolean, string, string, string, string] & {
      active: boolean
      master: string
      name: string
      description: string
      ABI: string
    })[]
  >

  callStatic: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>

    /**
     * Returns the admin role that controls `role`. See {grantRole} and {revokeRole}. To change a role's admin, use {_setRoleAdmin}.
     */
    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>

    /**
     * Returns one of the accounts that have `role`. `index` must be a value between 0 and {getRoleMemberCount}, non-inclusive. Role bearers are not sorted in any particular way, and their ordering may change at any point. WARNING: When using {getRoleMember} and {getRoleMemberCount}, make sure you perform all queries on the same block. See the following https://forum.openzeppelin.com/t/iterating-over-elements-on-enumerableset-in-openzeppelin-contracts/2296[forum post] for more information.
     */
    getRoleMember(role: BytesLike, index: BigNumberish, overrides?: CallOverrides): Promise<string>

    /**
     * Returns the number of accounts that have `role`. Can be used together with {getRoleMember} to enumerate all bearers of a role.
     */
    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    /**
     * Grants `role` to `account`. If `account` had not been already granted `role`, emits a {RoleGranted} event. Requirements: - the caller must have ``role``'s admin role.
     */
    grantRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<void>

    /**
     * Returns `true` if `account` has been granted `role`.
     */
    hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<boolean>

    /**
     * Revokes `role` from the calling account. Roles are often managed via {grantRole} and {revokeRole}: this function's purpose is to provide a mechanism for accounts to lose their privileges if they are compromised (such as when a trusted device is misplaced). If the calling account had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must be `account`.
     */
    renounceRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<void>

    /**
     * Revokes `role` from `account`. If `account` had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must have ``role``'s admin role.
     */
    revokeRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<void>

    addProject(name: string, description: string, overrides?: CallOverrides): Promise<BigNumber>

    delProject(name: string, overrides?: CallOverrides): Promise<boolean>

    updateProjectByName(
      name: string,
      activeProject: boolean,
      master: string,
      description: string,
      ABI: string,
      overrides?: CallOverrides,
    ): Promise<boolean>

    changeActive(overrides?: CallOverrides): Promise<boolean>

    exists(name: string, overrides?: CallOverrides): Promise<boolean>

    isActive(name: string, overrides?: CallOverrides): Promise<boolean>

    getProjectByName(
      name: string,
      overrides?: CallOverrides,
    ): Promise<
      [boolean, string, string, string, string] & {
        active: boolean
        master: string
        name: string
        description: string
        ABI: string
      }
    >

    getMasterAddressByName(name: string, overrides?: CallOverrides): Promise<string>

    getProjectByIndex(
      index: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [boolean, string, string, string, string] & {
        active: boolean
        master: string
        name: string
        description: string
        ABI: string
      }
    >

    getIndexByName(name: string, overrides?: CallOverrides): Promise<BigNumber>

    countProjects(overrides?: CallOverrides): Promise<BigNumber>

    listProjects(
      overrides?: CallOverrides,
    ): Promise<
      ([boolean, string, string, string, string] & {
        active: boolean
        master: string
        name: string
        description: string
        ABI: string
      })[]
    >
  }

  filters: {
    ProjectAdded(
      name?: null,
      description?: null,
    ): TypedEventFilter<[string, string], { name: string; description: string }>

    ProjectDeleted(name?: null): TypedEventFilter<[string], { name: string }>

    ProjectUpdated(
      name?: null,
      description?: null,
      master?: string | null,
      active?: null,
    ): TypedEventFilter<
      [string, string, string, boolean],
      { name: string; description: string; master: string; active: boolean }
    >

    RoleAdminChanged(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null,
    ): TypedEventFilter<[string, string, string], { role: string; previousAdminRole: string; newAdminRole: string }>

    RoleGranted(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null,
    ): TypedEventFilter<[string, string, string], { role: string; account: string; sender: string }>

    RoleRevoked(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null,
    ): TypedEventFilter<[string, string, string], { role: string; account: string; sender: string }>
  }

  estimateGas: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>

    /**
     * Returns the admin role that controls `role`. See {grantRole} and {revokeRole}. To change a role's admin, use {_setRoleAdmin}.
     */
    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    /**
     * Returns one of the accounts that have `role`. `index` must be a value between 0 and {getRoleMemberCount}, non-inclusive. Role bearers are not sorted in any particular way, and their ordering may change at any point. WARNING: When using {getRoleMember} and {getRoleMemberCount}, make sure you perform all queries on the same block. See the following https://forum.openzeppelin.com/t/iterating-over-elements-on-enumerableset-in-openzeppelin-contracts/2296[forum post] for more information.
     */
    getRoleMember(role: BytesLike, index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    /**
     * Returns the number of accounts that have `role`. Can be used together with {getRoleMember} to enumerate all bearers of a role.
     */
    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    /**
     * Grants `role` to `account`. If `account` had not been already granted `role`, emits a {RoleGranted} event. Requirements: - the caller must have ``role``'s admin role.
     */
    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    /**
     * Returns `true` if `account` has been granted `role`.
     */
    hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<BigNumber>

    /**
     * Revokes `role` from the calling account. Roles are often managed via {grantRole} and {revokeRole}: this function's purpose is to provide a mechanism for accounts to lose their privileges if they are compromised (such as when a trusted device is misplaced). If the calling account had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must be `account`.
     */
    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    /**
     * Revokes `role` from `account`. If `account` had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must have ``role``'s admin role.
     */
    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    addProject(
      name: string,
      description: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    delProject(name: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>

    updateProjectByName(
      name: string,
      activeProject: boolean,
      master: string,
      description: string,
      ABI: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    changeActive(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>

    exists(name: string, overrides?: CallOverrides): Promise<BigNumber>

    isActive(name: string, overrides?: CallOverrides): Promise<BigNumber>

    getProjectByName(name: string, overrides?: CallOverrides): Promise<BigNumber>

    getMasterAddressByName(name: string, overrides?: CallOverrides): Promise<BigNumber>

    getProjectByIndex(index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    getIndexByName(name: string, overrides?: CallOverrides): Promise<BigNumber>

    countProjects(overrides?: CallOverrides): Promise<BigNumber>

    listProjects(overrides?: CallOverrides): Promise<BigNumber>
  }

  populateTransaction: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>

    /**
     * Returns the admin role that controls `role`. See {grantRole} and {revokeRole}. To change a role's admin, use {_setRoleAdmin}.
     */
    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>

    /**
     * Returns one of the accounts that have `role`. `index` must be a value between 0 and {getRoleMemberCount}, non-inclusive. Role bearers are not sorted in any particular way, and their ordering may change at any point. WARNING: When using {getRoleMember} and {getRoleMemberCount}, make sure you perform all queries on the same block. See the following https://forum.openzeppelin.com/t/iterating-over-elements-on-enumerableset-in-openzeppelin-contracts/2296[forum post] for more information.
     */
    getRoleMember(role: BytesLike, index: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    /**
     * Returns the number of accounts that have `role`. Can be used together with {getRoleMember} to enumerate all bearers of a role.
     */
    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>

    /**
     * Grants `role` to `account`. If `account` had not been already granted `role`, emits a {RoleGranted} event. Requirements: - the caller must have ``role``'s admin role.
     */
    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    /**
     * Returns `true` if `account` has been granted `role`.
     */
    hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    /**
     * Revokes `role` from the calling account. Roles are often managed via {grantRole} and {revokeRole}: this function's purpose is to provide a mechanism for accounts to lose their privileges if they are compromised (such as when a trusted device is misplaced). If the calling account had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must be `account`.
     */
    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    /**
     * Revokes `role` from `account`. If `account` had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must have ``role``'s admin role.
     */
    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    addProject(
      name: string,
      description: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    delProject(name: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>

    updateProjectByName(
      name: string,
      activeProject: boolean,
      master: string,
      description: string,
      ABI: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    changeActive(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>

    exists(name: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    isActive(name: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    getProjectByName(name: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    getMasterAddressByName(name: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    getProjectByIndex(index: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    getIndexByName(name: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    countProjects(overrides?: CallOverrides): Promise<PopulatedTransaction>

    listProjects(overrides?: CallOverrides): Promise<PopulatedTransaction>
  }
}
