/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from 'ethers'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'
import { TypedEventFilter, TypedEvent, TypedListener } from './commons'

export interface MasterQuoteInterface extends ethers.utils.Interface {
  functions: {
    'DEFAULT_ADMIN_ROLE()': FunctionFragment
    'getRoleAdmin(bytes32)': FunctionFragment
    'getRoleMember(bytes32,uint256)': FunctionFragment
    'getRoleMemberCount(bytes32)': FunctionFragment
    'grantRole(bytes32,address)': FunctionFragment
    'hasRole(bytes32,address)': FunctionFragment
    'renounceRole(bytes32,address)': FunctionFragment
    'revokeRole(bytes32,address)': FunctionFragment
    'studentList()': FunctionFragment
    'validate(address)': FunctionFragment
    'validateBySC(address,address)': FunctionFragment
    'deleteProject()': FunctionFragment
    'deleteProjectBySC(address)': FunctionFragment
    'updateStudentList(address)': FunctionFragment
    'existsOwner(address)': FunctionFragment
    'existsScProject(address)': FunctionFragment
    'listProjectsInfo()': FunctionFragment
    'countProjects()': FunctionFragment
    'getProjectByIndex(uint256)': FunctionFragment
    'getProjectByOwner(address)': FunctionFragment
  }

  encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string
  encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string
  encodeFunctionData(functionFragment: 'getRoleMember', values: [BytesLike, BigNumberish]): string
  encodeFunctionData(functionFragment: 'getRoleMemberCount', values: [BytesLike]): string
  encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 'studentList', values?: undefined): string
  encodeFunctionData(functionFragment: 'validate', values: [string]): string
  encodeFunctionData(functionFragment: 'validateBySC', values: [string, string]): string
  encodeFunctionData(functionFragment: 'deleteProject', values?: undefined): string
  encodeFunctionData(functionFragment: 'deleteProjectBySC', values: [string]): string
  encodeFunctionData(functionFragment: 'updateStudentList', values: [string]): string
  encodeFunctionData(functionFragment: 'existsOwner', values: [string]): string
  encodeFunctionData(functionFragment: 'existsScProject', values: [string]): string
  encodeFunctionData(functionFragment: 'listProjectsInfo', values?: undefined): string
  encodeFunctionData(functionFragment: 'countProjects', values?: undefined): string
  encodeFunctionData(functionFragment: 'getProjectByIndex', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'getProjectByOwner', values: [string]): string

  decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getRoleMember', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getRoleMemberCount', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'studentList', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'validate', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'validateBySC', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'deleteProject', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'deleteProjectBySC', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'updateStudentList', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'existsOwner', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'existsScProject', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'listProjectsInfo', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'countProjects', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getProjectByIndex', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getProjectByOwner', data: BytesLike): Result

  events: {
    'ProjectAdded(address,address)': EventFragment
    'ProjectDeleted(address,address)': EventFragment
    'RoleAdminChanged(bytes32,bytes32,bytes32)': EventFragment
    'RoleGranted(bytes32,address,address)': EventFragment
    'RoleRevoked(bytes32,address,address)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'ProjectAdded'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'ProjectDeleted'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RoleAdminChanged'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RoleGranted'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RoleRevoked'): EventFragment
}

export interface MasterQuoteType extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>,
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
  ): this

  listeners(eventName?: string): Array<Listener>
  off(eventName: string, listener: Listener): this
  on(eventName: string, listener: Listener): this
  once(eventName: string, listener: Listener): this
  removeListener(eventName: string, listener: Listener): this
  removeAllListeners(eventName?: string): this

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>

  interface: MasterQuoteInterface

  functions: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>

    /**
     * Returns the admin role that controls `role`. See {grantRole} and {revokeRole}. To change a role's admin, use {_setRoleAdmin}.
     */
    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>

    /**
     * Returns one of the accounts that have `role`. `index` must be a value between 0 and {getRoleMemberCount}, non-inclusive. Role bearers are not sorted in any particular way, and their ordering may change at any point. WARNING: When using {getRoleMember} and {getRoleMemberCount}, make sure you perform all queries on the same block. See the following https://forum.openzeppelin.com/t/iterating-over-elements-on-enumerableset-in-openzeppelin-contracts/2296[forum post] for more information.
     */
    getRoleMember(role: BytesLike, index: BigNumberish, overrides?: CallOverrides): Promise<[string]>

    /**
     * Returns the number of accounts that have `role`. Can be used together with {getRoleMember} to enumerate all bearers of a role.
     */
    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<[BigNumber]>

    /**
     * Grants `role` to `account`. If `account` had not been already granted `role`, emits a {RoleGranted} event. Requirements: - the caller must have ``role``'s admin role.
     */
    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    /**
     * Returns `true` if `account` has been granted `role`.
     */
    hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<[boolean]>

    /**
     * Revokes `role` from the calling account. Roles are often managed via {grantRole} and {revokeRole}: this function's purpose is to provide a mechanism for accounts to lose their privileges if they are compromised (such as when a trusted device is misplaced). If the calling account had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must be `account`.
     */
    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    /**
     * Revokes `role` from `account`. If `account` had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must have ``role``'s admin role.
     */
    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    studentList(overrides?: CallOverrides): Promise<[string]>

    validate(
      scProjectAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    validateBySC(
      scOwner: string,
      scProjectAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    deleteProject(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

    deleteProjectBySC(
      scOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    updateStudentList(
      addressStudentList: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    existsOwner(account: string, overrides?: CallOverrides): Promise<[boolean]>

    existsScProject(scAddress: string, overrides?: CallOverrides): Promise<[boolean]>

    listProjectsInfo(
      overrides?: CallOverrides,
    ): Promise<
      [
        ([string, string, string] & {
          owner: string
          scProject: string
          info: string
        })[],
      ]
    >

    countProjects(overrides?: CallOverrides): Promise<[BigNumber]>

    getProjectByIndex(
      index: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [
        [string, string, string] & {
          owner: string
          scProject: string
          info: string
        },
      ]
    >

    getProjectByOwner(
      scOwner: string,
      overrides?: CallOverrides,
    ): Promise<
      [
        [string, string, string] & {
          owner: string
          scProject: string
          info: string
        },
      ]
    >
  }

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>

  /**
   * Returns the admin role that controls `role`. See {grantRole} and {revokeRole}. To change a role's admin, use {_setRoleAdmin}.
   */
  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>

  /**
   * Returns one of the accounts that have `role`. `index` must be a value between 0 and {getRoleMemberCount}, non-inclusive. Role bearers are not sorted in any particular way, and their ordering may change at any point. WARNING: When using {getRoleMember} and {getRoleMemberCount}, make sure you perform all queries on the same block. See the following https://forum.openzeppelin.com/t/iterating-over-elements-on-enumerableset-in-openzeppelin-contracts/2296[forum post] for more information.
   */
  getRoleMember(role: BytesLike, index: BigNumberish, overrides?: CallOverrides): Promise<string>

  /**
   * Returns the number of accounts that have `role`. Can be used together with {getRoleMember} to enumerate all bearers of a role.
   */
  getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

  /**
   * Grants `role` to `account`. If `account` had not been already granted `role`, emits a {RoleGranted} event. Requirements: - the caller must have ``role``'s admin role.
   */
  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  /**
   * Returns `true` if `account` has been granted `role`.
   */
  hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<boolean>

  /**
   * Revokes `role` from the calling account. Roles are often managed via {grantRole} and {revokeRole}: this function's purpose is to provide a mechanism for accounts to lose their privileges if they are compromised (such as when a trusted device is misplaced). If the calling account had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must be `account`.
   */
  renounceRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  /**
   * Revokes `role` from `account`. If `account` had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must have ``role``'s admin role.
   */
  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  studentList(overrides?: CallOverrides): Promise<string>

  validate(
    scProjectAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  validateBySC(
    scOwner: string,
    scProjectAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  deleteProject(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

  deleteProjectBySC(
    scOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  updateStudentList(
    addressStudentList: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  existsOwner(account: string, overrides?: CallOverrides): Promise<boolean>

  existsScProject(scAddress: string, overrides?: CallOverrides): Promise<boolean>

  listProjectsInfo(
    overrides?: CallOverrides,
  ): Promise<
    ([string, string, string] & {
      owner: string
      scProject: string
      info: string
    })[]
  >

  countProjects(overrides?: CallOverrides): Promise<BigNumber>

  getProjectByIndex(
    index: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<
    [string, string, string] & {
      owner: string
      scProject: string
      info: string
    }
  >

  getProjectByOwner(
    scOwner: string,
    overrides?: CallOverrides,
  ): Promise<
    [string, string, string] & {
      owner: string
      scProject: string
      info: string
    }
  >

  callStatic: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>

    /**
     * Returns the admin role that controls `role`. See {grantRole} and {revokeRole}. To change a role's admin, use {_setRoleAdmin}.
     */
    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>

    /**
     * Returns one of the accounts that have `role`. `index` must be a value between 0 and {getRoleMemberCount}, non-inclusive. Role bearers are not sorted in any particular way, and their ordering may change at any point. WARNING: When using {getRoleMember} and {getRoleMemberCount}, make sure you perform all queries on the same block. See the following https://forum.openzeppelin.com/t/iterating-over-elements-on-enumerableset-in-openzeppelin-contracts/2296[forum post] for more information.
     */
    getRoleMember(role: BytesLike, index: BigNumberish, overrides?: CallOverrides): Promise<string>

    /**
     * Returns the number of accounts that have `role`. Can be used together with {getRoleMember} to enumerate all bearers of a role.
     */
    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    /**
     * Grants `role` to `account`. If `account` had not been already granted `role`, emits a {RoleGranted} event. Requirements: - the caller must have ``role``'s admin role.
     */
    grantRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<void>

    /**
     * Returns `true` if `account` has been granted `role`.
     */
    hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<boolean>

    /**
     * Revokes `role` from the calling account. Roles are often managed via {grantRole} and {revokeRole}: this function's purpose is to provide a mechanism for accounts to lose their privileges if they are compromised (such as when a trusted device is misplaced). If the calling account had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must be `account`.
     */
    renounceRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<void>

    /**
     * Revokes `role` from `account`. If `account` had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must have ``role``'s admin role.
     */
    revokeRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<void>

    studentList(overrides?: CallOverrides): Promise<string>

    validate(scProjectAddress: string, overrides?: CallOverrides): Promise<boolean>

    validateBySC(scOwner: string, scProjectAddress: string, overrides?: CallOverrides): Promise<boolean>

    deleteProject(overrides?: CallOverrides): Promise<boolean>

    deleteProjectBySC(scOwner: string, overrides?: CallOverrides): Promise<boolean>

    updateStudentList(addressStudentList: string, overrides?: CallOverrides): Promise<boolean>

    existsOwner(account: string, overrides?: CallOverrides): Promise<boolean>

    existsScProject(scAddress: string, overrides?: CallOverrides): Promise<boolean>

    listProjectsInfo(
      overrides?: CallOverrides,
    ): Promise<
      ([string, string, string] & {
        owner: string
        scProject: string
        info: string
      })[]
    >

    countProjects(overrides?: CallOverrides): Promise<BigNumber>

    getProjectByIndex(
      index: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [string, string, string] & {
        owner: string
        scProject: string
        info: string
      }
    >

    getProjectByOwner(
      scOwner: string,
      overrides?: CallOverrides,
    ): Promise<
      [string, string, string] & {
        owner: string
        scProject: string
        info: string
      }
    >
  }

  filters: {
    ProjectAdded(
      owner?: string | null,
      scProject?: string | null,
    ): TypedEventFilter<[string, string], { owner: string; scProject: string }>

    ProjectDeleted(
      owner?: string | null,
      scProject?: string | null,
    ): TypedEventFilter<[string, string], { owner: string; scProject: string }>

    RoleAdminChanged(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null,
    ): TypedEventFilter<[string, string, string], { role: string; previousAdminRole: string; newAdminRole: string }>

    RoleGranted(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null,
    ): TypedEventFilter<[string, string, string], { role: string; account: string; sender: string }>

    RoleRevoked(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null,
    ): TypedEventFilter<[string, string, string], { role: string; account: string; sender: string }>
  }

  estimateGas: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>

    /**
     * Returns the admin role that controls `role`. See {grantRole} and {revokeRole}. To change a role's admin, use {_setRoleAdmin}.
     */
    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    /**
     * Returns one of the accounts that have `role`. `index` must be a value between 0 and {getRoleMemberCount}, non-inclusive. Role bearers are not sorted in any particular way, and their ordering may change at any point. WARNING: When using {getRoleMember} and {getRoleMemberCount}, make sure you perform all queries on the same block. See the following https://forum.openzeppelin.com/t/iterating-over-elements-on-enumerableset-in-openzeppelin-contracts/2296[forum post] for more information.
     */
    getRoleMember(role: BytesLike, index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    /**
     * Returns the number of accounts that have `role`. Can be used together with {getRoleMember} to enumerate all bearers of a role.
     */
    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    /**
     * Grants `role` to `account`. If `account` had not been already granted `role`, emits a {RoleGranted} event. Requirements: - the caller must have ``role``'s admin role.
     */
    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    /**
     * Returns `true` if `account` has been granted `role`.
     */
    hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<BigNumber>

    /**
     * Revokes `role` from the calling account. Roles are often managed via {grantRole} and {revokeRole}: this function's purpose is to provide a mechanism for accounts to lose their privileges if they are compromised (such as when a trusted device is misplaced). If the calling account had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must be `account`.
     */
    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    /**
     * Revokes `role` from `account`. If `account` had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must have ``role``'s admin role.
     */
    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    studentList(overrides?: CallOverrides): Promise<BigNumber>

    validate(scProjectAddress: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>

    validateBySC(
      scOwner: string,
      scProjectAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    deleteProject(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>

    deleteProjectBySC(scOwner: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>

    updateStudentList(
      addressStudentList: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    existsOwner(account: string, overrides?: CallOverrides): Promise<BigNumber>

    existsScProject(scAddress: string, overrides?: CallOverrides): Promise<BigNumber>

    listProjectsInfo(overrides?: CallOverrides): Promise<BigNumber>

    countProjects(overrides?: CallOverrides): Promise<BigNumber>

    getProjectByIndex(index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    getProjectByOwner(scOwner: string, overrides?: CallOverrides): Promise<BigNumber>
  }

  populateTransaction: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>

    /**
     * Returns the admin role that controls `role`. See {grantRole} and {revokeRole}. To change a role's admin, use {_setRoleAdmin}.
     */
    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>

    /**
     * Returns one of the accounts that have `role`. `index` must be a value between 0 and {getRoleMemberCount}, non-inclusive. Role bearers are not sorted in any particular way, and their ordering may change at any point. WARNING: When using {getRoleMember} and {getRoleMemberCount}, make sure you perform all queries on the same block. See the following https://forum.openzeppelin.com/t/iterating-over-elements-on-enumerableset-in-openzeppelin-contracts/2296[forum post] for more information.
     */
    getRoleMember(role: BytesLike, index: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    /**
     * Returns the number of accounts that have `role`. Can be used together with {getRoleMember} to enumerate all bearers of a role.
     */
    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>

    /**
     * Grants `role` to `account`. If `account` had not been already granted `role`, emits a {RoleGranted} event. Requirements: - the caller must have ``role``'s admin role.
     */
    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    /**
     * Returns `true` if `account` has been granted `role`.
     */
    hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    /**
     * Revokes `role` from the calling account. Roles are often managed via {grantRole} and {revokeRole}: this function's purpose is to provide a mechanism for accounts to lose their privileges if they are compromised (such as when a trusted device is misplaced). If the calling account had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must be `account`.
     */
    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    /**
     * Revokes `role` from `account`. If `account` had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must have ``role``'s admin role.
     */
    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    studentList(overrides?: CallOverrides): Promise<PopulatedTransaction>

    validate(
      scProjectAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    validateBySC(
      scOwner: string,
      scProjectAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    deleteProject(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>

    deleteProjectBySC(
      scOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    updateStudentList(
      addressStudentList: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    existsOwner(account: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    existsScProject(scAddress: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    listProjectsInfo(overrides?: CallOverrides): Promise<PopulatedTransaction>

    countProjects(overrides?: CallOverrides): Promise<PopulatedTransaction>

    getProjectByIndex(index: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    getProjectByOwner(scOwner: string, overrides?: CallOverrides): Promise<PopulatedTransaction>
  }
}
