/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from 'ethers'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'
import { TypedEventFilter, TypedEvent, TypedListener } from './commons'

export interface StudentPortfolioInterface extends ethers.utils.Interface {
  functions: {
    'DEFAULT_ADMIN_ROLE()': FunctionFragment
    'getRoleAdmin(bytes32)': FunctionFragment
    'getRoleMember(bytes32,uint256)': FunctionFragment
    'getRoleMemberCount(bytes32)': FunctionFragment
    'grantRole(bytes32,address)': FunctionFragment
    'hasRole(bytes32,address)': FunctionFragment
    'projectList()': FunctionFragment
    'renounceRole(bytes32,address)': FunctionFragment
    'revokeRole(bytes32,address)': FunctionFragment
    'student()': FunctionFragment
    'addProject(address,string)': FunctionFragment
    'deleteProjectByAddress(address)': FunctionFragment
    'updateProjectList(address)': FunctionFragment
    'addressInPortfolio(address)': FunctionFragment
    'nameInPortfolio(string)': FunctionFragment
    'listPortfolio()': FunctionFragment
    'countPortfolio()': FunctionFragment
    'projectByName(string)': FunctionFragment
    'projectByAddress(address)': FunctionFragment
    'projectByIndex(uint256)': FunctionFragment
    'indexOfProject(address)': FunctionFragment
  }

  encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string
  encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string
  encodeFunctionData(functionFragment: 'getRoleMember', values: [BytesLike, BigNumberish]): string
  encodeFunctionData(functionFragment: 'getRoleMemberCount', values: [BytesLike]): string
  encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 'projectList', values?: undefined): string
  encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 'student', values?: undefined): string
  encodeFunctionData(functionFragment: 'addProject', values: [string, string]): string
  encodeFunctionData(functionFragment: 'deleteProjectByAddress', values: [string]): string
  encodeFunctionData(functionFragment: 'updateProjectList', values: [string]): string
  encodeFunctionData(functionFragment: 'addressInPortfolio', values: [string]): string
  encodeFunctionData(functionFragment: 'nameInPortfolio', values: [string]): string
  encodeFunctionData(functionFragment: 'listPortfolio', values?: undefined): string
  encodeFunctionData(functionFragment: 'countPortfolio', values?: undefined): string
  encodeFunctionData(functionFragment: 'projectByName', values: [string]): string
  encodeFunctionData(functionFragment: 'projectByAddress', values: [string]): string
  encodeFunctionData(functionFragment: 'projectByIndex', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'indexOfProject', values: [string]): string

  decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getRoleMember', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getRoleMemberCount', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'projectList', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'student', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'addProject', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'deleteProjectByAddress', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'updateProjectList', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'addressInPortfolio', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'nameInPortfolio', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'listPortfolio', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'countPortfolio', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'projectByName', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'projectByAddress', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'projectByIndex', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'indexOfProject', data: BytesLike): Result

  events: {
    'PortfolioProjectAdded(address,string)': EventFragment
    'PortfolioProjectDeleted(address,string)': EventFragment
    'RoleAdminChanged(bytes32,bytes32,bytes32)': EventFragment
    'RoleGranted(bytes32,address,address)': EventFragment
    'RoleRevoked(bytes32,address,address)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'PortfolioProjectAdded'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'PortfolioProjectDeleted'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RoleAdminChanged'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RoleGranted'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RoleRevoked'): EventFragment
}

export interface StudentPortfolioType extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>,
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
  ): this

  listeners(eventName?: string): Array<Listener>
  off(eventName: string, listener: Listener): this
  on(eventName: string, listener: Listener): this
  once(eventName: string, listener: Listener): this
  removeListener(eventName: string, listener: Listener): this
  removeAllListeners(eventName?: string): this

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>

  interface: StudentPortfolioInterface

  functions: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>

    /**
     * Returns the admin role that controls `role`. See {grantRole} and {revokeRole}. To change a role's admin, use {_setRoleAdmin}.
     */
    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>

    /**
     * Returns one of the accounts that have `role`. `index` must be a value between 0 and {getRoleMemberCount}, non-inclusive. Role bearers are not sorted in any particular way, and their ordering may change at any point. WARNING: When using {getRoleMember} and {getRoleMemberCount}, make sure you perform all queries on the same block. See the following https://forum.openzeppelin.com/t/iterating-over-elements-on-enumerableset-in-openzeppelin-contracts/2296[forum post] for more information.
     */
    getRoleMember(role: BytesLike, index: BigNumberish, overrides?: CallOverrides): Promise<[string]>

    /**
     * Returns the number of accounts that have `role`. Can be used together with {getRoleMember} to enumerate all bearers of a role.
     */
    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<[BigNumber]>

    /**
     * Grants `role` to `account`. If `account` had not been already granted `role`, emits a {RoleGranted} event. Requirements: - the caller must have ``role``'s admin role.
     */
    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    /**
     * Returns `true` if `account` has been granted `role`.
     */
    hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<[boolean]>

    projectList(overrides?: CallOverrides): Promise<[string]>

    /**
     * Revokes `role` from the calling account. Roles are often managed via {grantRole} and {revokeRole}: this function's purpose is to provide a mechanism for accounts to lose their privileges if they are compromised (such as when a trusted device is misplaced). If the calling account had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must be `account`.
     */
    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    /**
     * Revokes `role` from `account`. If `account` had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must have ``role``'s admin role.
     */
    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    student(overrides?: CallOverrides): Promise<[string]>

    addProject(
      projectAddress: string,
      projectName: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    deleteProjectByAddress(
      projectAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    updateProjectList(
      addressProjectList: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    addressInPortfolio(projectAddress: string, overrides?: CallOverrides): Promise<[boolean]>

    nameInPortfolio(projectName: string, overrides?: CallOverrides): Promise<[boolean]>

    listPortfolio(overrides?: CallOverrides): Promise<[([string, string] & { projectAddress: string; name: string })[]]>

    countPortfolio(overrides?: CallOverrides): Promise<[BigNumber]>

    projectByName(
      projectName: string,
      overrides?: CallOverrides,
    ): Promise<[[string, string] & { projectAddress: string; name: string }]>

    projectByAddress(
      projectAddress: string,
      overrides?: CallOverrides,
    ): Promise<[[string, string] & { projectAddress: string; name: string }]>

    projectByIndex(
      index: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[[string, string] & { projectAddress: string; name: string }]>

    indexOfProject(projectAddress: string, overrides?: CallOverrides): Promise<[BigNumber]>
  }

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>

  /**
   * Returns the admin role that controls `role`. See {grantRole} and {revokeRole}. To change a role's admin, use {_setRoleAdmin}.
   */
  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>

  /**
   * Returns one of the accounts that have `role`. `index` must be a value between 0 and {getRoleMemberCount}, non-inclusive. Role bearers are not sorted in any particular way, and their ordering may change at any point. WARNING: When using {getRoleMember} and {getRoleMemberCount}, make sure you perform all queries on the same block. See the following https://forum.openzeppelin.com/t/iterating-over-elements-on-enumerableset-in-openzeppelin-contracts/2296[forum post] for more information.
   */
  getRoleMember(role: BytesLike, index: BigNumberish, overrides?: CallOverrides): Promise<string>

  /**
   * Returns the number of accounts that have `role`. Can be used together with {getRoleMember} to enumerate all bearers of a role.
   */
  getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

  /**
   * Grants `role` to `account`. If `account` had not been already granted `role`, emits a {RoleGranted} event. Requirements: - the caller must have ``role``'s admin role.
   */
  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  /**
   * Returns `true` if `account` has been granted `role`.
   */
  hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<boolean>

  projectList(overrides?: CallOverrides): Promise<string>

  /**
   * Revokes `role` from the calling account. Roles are often managed via {grantRole} and {revokeRole}: this function's purpose is to provide a mechanism for accounts to lose their privileges if they are compromised (such as when a trusted device is misplaced). If the calling account had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must be `account`.
   */
  renounceRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  /**
   * Revokes `role` from `account`. If `account` had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must have ``role``'s admin role.
   */
  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  student(overrides?: CallOverrides): Promise<string>

  addProject(
    projectAddress: string,
    projectName: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  deleteProjectByAddress(
    projectAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  updateProjectList(
    addressProjectList: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  addressInPortfolio(projectAddress: string, overrides?: CallOverrides): Promise<boolean>

  nameInPortfolio(projectName: string, overrides?: CallOverrides): Promise<boolean>

  listPortfolio(overrides?: CallOverrides): Promise<([string, string] & { projectAddress: string; name: string })[]>

  countPortfolio(overrides?: CallOverrides): Promise<BigNumber>

  projectByName(
    projectName: string,
    overrides?: CallOverrides,
  ): Promise<[string, string] & { projectAddress: string; name: string }>

  projectByAddress(
    projectAddress: string,
    overrides?: CallOverrides,
  ): Promise<[string, string] & { projectAddress: string; name: string }>

  projectByIndex(
    index: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<[string, string] & { projectAddress: string; name: string }>

  indexOfProject(projectAddress: string, overrides?: CallOverrides): Promise<BigNumber>

  callStatic: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>

    /**
     * Returns the admin role that controls `role`. See {grantRole} and {revokeRole}. To change a role's admin, use {_setRoleAdmin}.
     */
    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>

    /**
     * Returns one of the accounts that have `role`. `index` must be a value between 0 and {getRoleMemberCount}, non-inclusive. Role bearers are not sorted in any particular way, and their ordering may change at any point. WARNING: When using {getRoleMember} and {getRoleMemberCount}, make sure you perform all queries on the same block. See the following https://forum.openzeppelin.com/t/iterating-over-elements-on-enumerableset-in-openzeppelin-contracts/2296[forum post] for more information.
     */
    getRoleMember(role: BytesLike, index: BigNumberish, overrides?: CallOverrides): Promise<string>

    /**
     * Returns the number of accounts that have `role`. Can be used together with {getRoleMember} to enumerate all bearers of a role.
     */
    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    /**
     * Grants `role` to `account`. If `account` had not been already granted `role`, emits a {RoleGranted} event. Requirements: - the caller must have ``role``'s admin role.
     */
    grantRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<void>

    /**
     * Returns `true` if `account` has been granted `role`.
     */
    hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<boolean>

    projectList(overrides?: CallOverrides): Promise<string>

    /**
     * Revokes `role` from the calling account. Roles are often managed via {grantRole} and {revokeRole}: this function's purpose is to provide a mechanism for accounts to lose their privileges if they are compromised (such as when a trusted device is misplaced). If the calling account had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must be `account`.
     */
    renounceRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<void>

    /**
     * Revokes `role` from `account`. If `account` had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must have ``role``'s admin role.
     */
    revokeRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<void>

    student(overrides?: CallOverrides): Promise<string>

    addProject(projectAddress: string, projectName: string, overrides?: CallOverrides): Promise<BigNumber>

    deleteProjectByAddress(projectAddress: string, overrides?: CallOverrides): Promise<boolean>

    updateProjectList(addressProjectList: string, overrides?: CallOverrides): Promise<boolean>

    addressInPortfolio(projectAddress: string, overrides?: CallOverrides): Promise<boolean>

    nameInPortfolio(projectName: string, overrides?: CallOverrides): Promise<boolean>

    listPortfolio(overrides?: CallOverrides): Promise<([string, string] & { projectAddress: string; name: string })[]>

    countPortfolio(overrides?: CallOverrides): Promise<BigNumber>

    projectByName(
      projectName: string,
      overrides?: CallOverrides,
    ): Promise<[string, string] & { projectAddress: string; name: string }>

    projectByAddress(
      projectAddress: string,
      overrides?: CallOverrides,
    ): Promise<[string, string] & { projectAddress: string; name: string }>

    projectByIndex(
      index: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[string, string] & { projectAddress: string; name: string }>

    indexOfProject(projectAddress: string, overrides?: CallOverrides): Promise<BigNumber>
  }

  filters: {
    PortfolioProjectAdded(
      projectAddress?: string | null,
      projectName?: null,
    ): TypedEventFilter<[string, string], { projectAddress: string; projectName: string }>

    PortfolioProjectDeleted(
      projectAddress?: string | null,
      projectName?: null,
    ): TypedEventFilter<[string, string], { projectAddress: string; projectName: string }>

    RoleAdminChanged(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null,
    ): TypedEventFilter<[string, string, string], { role: string; previousAdminRole: string; newAdminRole: string }>

    RoleGranted(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null,
    ): TypedEventFilter<[string, string, string], { role: string; account: string; sender: string }>

    RoleRevoked(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null,
    ): TypedEventFilter<[string, string, string], { role: string; account: string; sender: string }>
  }

  estimateGas: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>

    /**
     * Returns the admin role that controls `role`. See {grantRole} and {revokeRole}. To change a role's admin, use {_setRoleAdmin}.
     */
    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    /**
     * Returns one of the accounts that have `role`. `index` must be a value between 0 and {getRoleMemberCount}, non-inclusive. Role bearers are not sorted in any particular way, and their ordering may change at any point. WARNING: When using {getRoleMember} and {getRoleMemberCount}, make sure you perform all queries on the same block. See the following https://forum.openzeppelin.com/t/iterating-over-elements-on-enumerableset-in-openzeppelin-contracts/2296[forum post] for more information.
     */
    getRoleMember(role: BytesLike, index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    /**
     * Returns the number of accounts that have `role`. Can be used together with {getRoleMember} to enumerate all bearers of a role.
     */
    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    /**
     * Grants `role` to `account`. If `account` had not been already granted `role`, emits a {RoleGranted} event. Requirements: - the caller must have ``role``'s admin role.
     */
    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    /**
     * Returns `true` if `account` has been granted `role`.
     */
    hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<BigNumber>

    projectList(overrides?: CallOverrides): Promise<BigNumber>

    /**
     * Revokes `role` from the calling account. Roles are often managed via {grantRole} and {revokeRole}: this function's purpose is to provide a mechanism for accounts to lose their privileges if they are compromised (such as when a trusted device is misplaced). If the calling account had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must be `account`.
     */
    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    /**
     * Revokes `role` from `account`. If `account` had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must have ``role``'s admin role.
     */
    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    student(overrides?: CallOverrides): Promise<BigNumber>

    addProject(
      projectAddress: string,
      projectName: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    deleteProjectByAddress(
      projectAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    updateProjectList(
      addressProjectList: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    addressInPortfolio(projectAddress: string, overrides?: CallOverrides): Promise<BigNumber>

    nameInPortfolio(projectName: string, overrides?: CallOverrides): Promise<BigNumber>

    listPortfolio(overrides?: CallOverrides): Promise<BigNumber>

    countPortfolio(overrides?: CallOverrides): Promise<BigNumber>

    projectByName(projectName: string, overrides?: CallOverrides): Promise<BigNumber>

    projectByAddress(projectAddress: string, overrides?: CallOverrides): Promise<BigNumber>

    projectByIndex(index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    indexOfProject(projectAddress: string, overrides?: CallOverrides): Promise<BigNumber>
  }

  populateTransaction: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>

    /**
     * Returns the admin role that controls `role`. See {grantRole} and {revokeRole}. To change a role's admin, use {_setRoleAdmin}.
     */
    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>

    /**
     * Returns one of the accounts that have `role`. `index` must be a value between 0 and {getRoleMemberCount}, non-inclusive. Role bearers are not sorted in any particular way, and their ordering may change at any point. WARNING: When using {getRoleMember} and {getRoleMemberCount}, make sure you perform all queries on the same block. See the following https://forum.openzeppelin.com/t/iterating-over-elements-on-enumerableset-in-openzeppelin-contracts/2296[forum post] for more information.
     */
    getRoleMember(role: BytesLike, index: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    /**
     * Returns the number of accounts that have `role`. Can be used together with {getRoleMember} to enumerate all bearers of a role.
     */
    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>

    /**
     * Grants `role` to `account`. If `account` had not been already granted `role`, emits a {RoleGranted} event. Requirements: - the caller must have ``role``'s admin role.
     */
    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    /**
     * Returns `true` if `account` has been granted `role`.
     */
    hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    projectList(overrides?: CallOverrides): Promise<PopulatedTransaction>

    /**
     * Revokes `role` from the calling account. Roles are often managed via {grantRole} and {revokeRole}: this function's purpose is to provide a mechanism for accounts to lose their privileges if they are compromised (such as when a trusted device is misplaced). If the calling account had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must be `account`.
     */
    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    /**
     * Revokes `role` from `account`. If `account` had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must have ``role``'s admin role.
     */
    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    student(overrides?: CallOverrides): Promise<PopulatedTransaction>

    addProject(
      projectAddress: string,
      projectName: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    deleteProjectByAddress(
      projectAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    updateProjectList(
      addressProjectList: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    addressInPortfolio(projectAddress: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    nameInPortfolio(projectName: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    listPortfolio(overrides?: CallOverrides): Promise<PopulatedTransaction>

    countPortfolio(overrides?: CallOverrides): Promise<PopulatedTransaction>

    projectByName(projectName: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    projectByAddress(projectAddress: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    projectByIndex(index: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    indexOfProject(projectAddress: string, overrides?: CallOverrides): Promise<PopulatedTransaction>
  }
}
